### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ssoonmi** [NicolasESchneider/Discoded#1]
### Production README
- [x] should be your last MVP

### Servers
- [x] should be able to invite other users to a server
- [x] sending images to a server or to dm's should be a bonus feature, not an MVP

### Channels within Servers
- [x] should be a separate MVP from servers

### Live Chat
- [x] live chat should be a feature itself before/after you servers

### Voice Chat
- [x] this should be listed under bonus features, not MVP's

Great job! If you have any comments/concerns about any of this, comment below or Slack me!

**Comment by nicolaseschneider** [comment]
What do you mean by live chat? is that not the same as posts to channels? I mean all posts on a channel are technically live.

**Comment by ssoonmi** [comment]
Live chat means that you are using websockets to post to a channel. You can get messaging to work without it being live. You just need to continuously refresh the screen.

We make live chat separate because it is a complicated feature in itself.
