### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by ssoonmi** [NicolasESchneider/Discoded#2]
### memberships
- [x] user should only have one membership per server

### posts
- [x] `author` column on posts should be `author_id`

### dms
- [x] how are you going to do dms and group chats?

Great job on your schema! If you have any comments/concerns about any of this, comment below or Slack me!

**Comment by nicolaseschneider** [comment]
My though was dms and group chats would fall under the category of servers and channels just dressed differently. A DM is basically just a 2 person server/channel that has participants for a name.

**Comment by nicolaseschneider** [comment]
as far as one membership for server, that would be a custom validation to be sure that you dont have a user/server pair repeating itself correct? how should I denote that in the schema?

**Comment by ssoonmi** [comment]
> as far as one membership for server, that would be a custom validation to be sure that you dont have a user/server pair repeating itself correct? how should I denote that in the schema?

Yes. you would have to do a database level uniqueness validation, not just a model level validation.
